services:
  mysql-prod:
    container_name: flow-mysql
    build:
      context: ./
      dockerfile: Dockerfile.mysql
    restart: unless-stopped
    env_file: .env.mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker_volume/mysql/data:/var/lib/mysql
    # profiles: [initdb]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - flow-net

  express:
    container_name: flow-express
    build:
      context: ./
      dockerfile: Dockerfile.express
    ports:
      - "8080:3001"
    networks:
      - flow-net
    depends_on:
      mysql-prod:
        condition: service_healthy

networks:
  flow-net:
    name: flow-net
